version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: node:latest
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Jason-Wanxt/token-bridge-contracts/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          yarn install
          yarn build
          yarn test

workflows:
  my-custom-workflow:
    jobs:
      - contract-test