version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: node:16

jobs:
  contract-test:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          yarn install
          yarn build
          ls
          yarn test

workflows:
  my-custom-workflow:
    jobs:
      - contract-test